#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          4

yabai -m config active_window_border_color   0xff99C794
yabai -m config normal_window_border_color   0xff808080
yabai -m config insert_feedback_color        0xffC594C5
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off

# show digital colour meter topmost and on all spaces
# yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on

#launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"
# e.g. bind to key in skhd:
# ctrl + alt + cmd - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

echo "yabai configuration loaded.."
